# -*- coding: utf-8 -*-
"""Jhosef Anthony Quispe Huarilloclla-202211720

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U77xuFMtn8Tt24gBUlijynag7nAxnmjK

--------------------------------------------------------------------------------
**EJERCICIOS PROPUESTOS PARA RESOLVER-TAREA(10 EJERCICIOS)**

1.-Realice un diagrama de flujo y pseudocódigo que representen el algoritmo para obtener el área de un triángulo.
"""

#Definir variables
base:float
altura:float
area:float
#Datos de entrada
base=float(input("ingrese la base : "))
altura= float(input("ingrese la altura : "))
#Proceso
area=(base*altura)/2
#Datos de salida
print(f"el area del triangulo es : {area}")

"""2.-Una empresa que contrata personal requiere determinar la edad de las personas que solicitan trabajo, pero cuando se les realiza la entrevista sólo se les pregunta el año en que nacieron.  Realice el diagrama de flujo y pseudocódigo que represente el algoritmo para solucionar este problema."""

#Definir variables
ADN:float
ACT:float
edad:float
#Datos de entrada
ADN=float(input("ingrese el año de nacimiento : "))
ACT=float(input("ingrese el año actual: " ))
#Proceso
edad=ACT-ADN
#Datos de salida
print(f"su edad es : {edad}")

"""3.-Un estacionamiento requiere determinar el cobro que debe aplicar a las personas que lo utilizan. Considere que el cobro es con base en las horas que lo disponen y que las fracciones de hora se toman como completas."""

#Definir varialbles
precio:float
horas:float
total:float
#Datos de entrada
precio=float(input("ingrese el precio : "))
horas=float(input("ingrese las horas : "))
#Proceso
total=precio*round(horas)
#Datos de salida
print(f"el total es : {total}")

"""4.-Constructoras Juliaca requiere determinar cuánto cobrar por trabajos de pintura. Considere que se cobra por m2 y realice un diagrama de flujo y pseudocódigo que represente el algoritmo que le permita ir generando presupuestos para cada cliente."""

#Definir variables
mcuadrado=float
pago:float
cobro:float
#Datos de entrada
mcuadrado=float(input("ingrese los metros cuadrados : "))
pago=float(input("ingrese el pago por metro cuadrado : "))
#Proceso
cobro=mcuadrado*pago
#Daros de salida
print(f"el total a cobrar es : {cobro}")

"""5.-Se requiere determinar la hipotenusa de un triángulo rectángulo ¿cómo sería el diagrama de flujo y el pseudocódigo que represente el algoritmo para obtenerla? Recuerde que por Pitágoras c^ {2} =a^ {2} +b^ {2}"""

#Definir variables
CO=float
CA=float
hipotenusa=float
#Datos de entrada
CO=float(input("ingrese el cateto opuesto: " ))
CA=float(input("ingrese el cateto adyacente: "))
#Proceso
hipotenusa=(CO**2+CA**2)**1/2
#Datos de salida
print(f"la hipotenusa es : {hipotenusa}")

"""6.-Una compañía de autobuses requiere determinar el costo que tendrá el boleto de un viaje, esto basado en los kilómetros por recorrer y el costo es por kilómetro. Realice un diagrama de flujo y pseudocódigo que representen el algoritmo para tal fin."""

#Definir variables
kilometros=float
precio=float
costo=float
#Datos de entrada
kilometros=float(input("ingrese los kilometros: "))
precio=float(input("ingrese el precio por kilometro: "))
#Proceso
costo=kilometros*precio
#Datos de salida
print(f"el precio del boleto es : {costo}")

"""7.-Se requiere determinar el tiempo que tarda una persona en llegar de una ciudad a otra en bicicleta, considerando que lleva una velocidad constante. Realice un diagrama de flujo y pseudocódigo que represente el algoritmo para tal fin. """

#Definir variables
velocidad=float
distancia=float
tiempo=float
#Datos de entrada
velocidad=float(input("ingrese la velocidad constante : "))
distancia=float(input("ingrese la distancia en kilometros : "))
#Proceso
tiempo=distancia/velocidad
#Datos de salida
print(f"el tiempo que tarda una persona en llegar de una ciudad a otra en bicicleta es : {tiempo}")

"""8.-Se requiere determinar el costo que tendrá, el realizar una llamada telefónica con base en el tiempo que dura la llamada y el costo es por minuto. realice un diagrama de flujo y pseudocódigo que representen el algoritmo para tal fin."""

#Definir variables
tiempo_en_horas:float
tiempo_en_minutos:float
precio:float
costo:float
#Datos de entrada
tiempo_en_horas=float(input("ingrese el tiempo en horas que duro la llamada : "))
tiempo_en_minutos=float(input("ingrese el tiempo en minutos que duro la llamada : "))
precio=float(input("ingrese el precio por minuto de llamada : "))
#Proceso
costo1=(tiempo_en_horas*60)*precio
costo2=tiempo_en_minutos*precio
#Datos de salida
print(f"el precio por minuto en horas es : {costo1}")
print(f"el precio por minuto es : {costo2}")

"""9.-Seda Juliaca requiere determinar el pago que debe realizar una persona por el total de metros cúbicos de consumo de agua. Realice un diagrama de flujo y pseudocódigo que represente el algoritmo que permita determinar ese pago."""

#Definir variables
consumo=float
precio=float
total=float
#Datos de entrada
consumo=float(input("ingrese el consumo de agua en litros : "))
precio=float(input("ingrese el precio del agua por metro cubico : "))
#Proceso
metro_cubico=consumo/1000
total=metro_cubico*precio
#Datos de salida
print(f"el total que debe pagar una persona por metro cubico de agua es : {total}")

"""10.-Electro Puno requiere determinar el pago que debe realizar una persona por el consumo de energía eléctrica, la cual se mide en kilowatts(KW).  Realice un diagrama de flujo y pseudocódigo que represente el algoritmo que permita determinar ese pago. """

#Definir variables
kilowatts=float
precio=float
total=float
#Datos de entrada
kilowatts=float(input("escriba el consumo el kilowatts : "))
precio=float(input("escriba el precio por kilowatts : "))
#Proceso
total=kilowatts*precio
#Datos de salida
print(f"el total a pagar por kilowatts es : {total}")